services:

  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=parity  
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PRIVATE_KEY: ${PRIVATE_KEY}
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://postgres:mysecretpassword@postgres:5432/parity?sslmode=disable
    depends_on:
      - postgres
    volumes:
      - ./config:/app/config
    secrets:
      - private_key 
    restart: unless-stopped
 
secrets:
  private_key:
    file: ./private_key.txt
 

volumes:
  postgres-data:
    driver: local
