server:
  port:
  host:
  endpoint:

database:
  url: postgres://<username>:<password>@<host>:<port>/<database_name>

ethereum:
  rpc:
  chain_id:
  token_address:
  stake_wallet_address:

aws:
  region:
  bucket_name:

scheduler:
  interval:
